export const MONGO_URI =
  'mongodb://localhost:27017,localhost:27018,localhost:27019/momi-hebat?replicaSet=rs';
export const ALPHABET = [...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'];
export const JWT_KEY = 'jwt-secret';
export const APP_VERSION = 'v0.0.1';
export const URL_FRONTEND = ['http://localhost:3000', 'http://localhost:5000'];
export const URL_API = '/api';
export const URL_AUTH = `${URL_API}/users`;
export const URL_PENGGUNA = `${URL_API}/pengguna`;
export const URL_PERIODE = `${URL_API}/periode`;
export const URL_REFERENSI = `${URL_API}/referensi`;
export const URL_KARYAWAN = `${URL_API}/karyawan`;
export const URL_AGEN = `${URL_API}/agen`;
export const URL_BARANG = `${URL_API}/barang`;
export const URL_PAKET = `${URL_API}/paket`;
export const URL_TRANSAKSI_BARANG = `${URL_API}/transaksi-barang`;
export const URL_TRANSAKSI_SALDO = `${URL_API}/transaksi-saldo`;
